version: "3.9"
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HTTP Event Collector (HEC)
      - "9997:9997"   # Indexer input
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    volumes:
      - /mnt/disk2/splunk-data:/opt/splunk/var     # logs, indexed data
      - /mnt/disk2/splunk-etc:/opt/splunk/etc      # configs, users, apps
    restart: always