global:
  splunk:
    hec:
      host: 192.168.216.136
      port: 8088
      token: 47c72624-b2c2-441a-ac47-f9d9f231c7c5
      protocol: http
      indexName: "main"

splunk-kubernetes-logging:
  enabled: true

  fluentd:
    # path of logfiles, default /var/log/containers/*.log
    path: /var/log/containers/*.log
    # paths of logfiles to exclude. object type is array as per fluentd specification:
    # https://docs.fluentd.org/input/tail#exclude_path
    exclude_path:
      - /var/log/containers/kube-svc-redirect*.log
      - /var/log/containers/splunk*.log
      - /var/log/containers/*_kube-system_*.log
      
  rbac:
    create: true

  serviceAccount:
    create: true


  # Exclude Splunk/Fluentd logs to avoid ingestion loops
  containers:
    logFormatType: cri

splunk-kubernetes-metrics:
  enabled: false  # Deprecated

splunk-kubernetes-objects:
  enabled: false  # Deprecated

